# Generated by Django 5.2.7 on 2025-11-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="currency_code",
            field=models.CharField(default="PHP", max_length=3),
        ),
        migrations.AlterField(
            model_name="expense",
            name="currency_code",
            field=models.CharField(default="PHP", max_length=3),
        ),
        migrations.AlterField(
            model_name="income",
            name="currency_code",
            field=models.CharField(default="PHP", max_length=3),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="default_currency",
            field=models.CharField(default="PHP", max_length=3),
        ),
    ]
