# Generated by Django 5.2.7 on 2025-11-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyCache",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=15)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currency_cache",
            },
        ),
    ]
