# Generated by Django 5.2.7 on 2025-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0002_currencycache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                default="/static/img/icons/icon-default.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incomesource",
            name="icon",
            field=models.CharField(
                blank=True,
                default="/static/img/icons/icon-default.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(
                default="/static/img/avatars/avatar1.png", max_length=255
            ),
        ),
    ]
