# Generated by Django 5.2.7 on 2025-11-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "expense_tracker",
            "0003_alter_category_icon_alter_incomesource_icon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_predefined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incomesource",
            name="is_predefined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_predefined_data",
            field=models.BooleanField(default=False),
        ),
    ]
